### ISSUE TITLE
DataSequencer.process()

### ISSUE THREAD

**Issue by hackerekcah** [TUT-ARG/DCASE2017-baseline-system#13]
if i understand correctly
line322: 
     segment_end_frame = segment_start_frame + self.hop_size
should be:
     segment_end_frame = segment_start_frame + **self.frames**

the same with line319

**Comment by toni-heittola** [comment]
You are correct. This bug has been addressed now in commit b8aab57cbec9da693a7b1d00e66fc6f495faff5b.
