### ISSUE TITLE
Two channel

### ISSUE THREAD

**Issue by hackerekcah** [TUT-ARG/DCASE2017-baseline-system#14]
How to keep two channel features?
if I setup 
    mfcc:
        mono:false
    Stacking_recipe: mfcc
it wont go with two channel, and if i setup like
    Stacking_recipe: mfcc=0;mfcc=1
it will go two channel, but stacked instead.
so How can i get two channel without stack?

**Comment by toni-heittola** [comment]
The system does not support this type of feature handling directly. To implement this, you would need to bypass feature stacking in application_core.py. Depending a bit on what you want to do with these multichannel features, you could collect features from multiple channels together in system_training-method before feeding it to the Learner class or implement custom Learner class able to handle multiple feature streams.
