### ISSUE TITLE
How feature extraction is implemented on 10s audio?

### ISSUE THREAD

**Issue by YuanGongND** [TUT-ARG/DCASE2017-baseline-system#17]
For the acoustic scene classification task, according to the documention, 

> Frame size: 40 ms (with 50% hop size)

> Feature vector: 40 log mel-band energies in 5 consecutive frames = 200 values

> Classification unit: one file (10 seconds of audio).

But the audio is 10 second, which will have 500 frames (considering the overlap). How does the baseline system choose the 5 frames from the 10-second-audio? Thanks!!

**Comment by toni-heittola** [comment]
The system uses context windowing approach to capture temporal context. In this approach, 5 consecutive frames are concatenated as a single feature vector, and this process in done while sliding through the original feature matrix (size (40, 500) ). This process will result feature matrix with size (200, 500).
