### ISSUE TITLE
results of task3

### ISSUE THREAD

**Issue by icestoneking** [TUT-ARG/DCASE2017-baseline-system#21]
Why do we only include street evaluation datasets that contain reference data published for task 3,but not include the description in event class-wise results in https://tut-arg.github.io/DCASE2017-baseline-system/for detailed instruction,Brakes squeaking ,car,children,large vehicle,people speaking,people walking.How to get other datasets in the result？Looking forward to your reply~

**Comment by toni-heittola** [comment]
Sorry for late reply. As you might have found, the evaluation results can be found from DCASE2017 [challenge website](http://www.cs.tut.fi/sgn/arg/dcase2017/challenge/task-sound-event-detection-in-real-life-audio-results).

For the completeness, there results were added to the documentation of the baseline too in commit 59aed38eefa5c7f5da797bb45a02d37ae4ed5111.

**Comment by icestoneking** [comment]
Thank you very much for your reply~
