### ISSUE TITLE
Issue of running task2_cakir.py in the example folder.

### ISSUE THREAD

**Issue by hanmeng31** [TUT-ARG/DCASE2017-baseline-system#23]
When I try to run "python3 task2_cakir.py" in the example folder, I got the following error.

[Errno 2] No such file or directory: '/wrk/cakir/DONOTREMOVE/DCASE2017_task_2/feature_extractor/dataset_9b4fa58bf77c506a30da403feee94c39/parameters.yaml'

**Comment by dangpzanco** [comment]
You need to change lines 79 and 80 of task2_cakir.defaults.yaml to your own paths.

See [Line 79](https://github.com/TUT-ARG/DCASE2017-baseline-system/blob/master/examples/task2_cakir.defaults.yaml#L79)

PS: I don't remember which path it needs, but one probably is the dataset root folder.

**Comment by hanmeng31** [comment]
Hi Daniel,

Thanks! I put the path there. But the program has another problem when trying to download data. I got the following error:

Download package list    :   0%|                               [E] TUTRareSoundEvents_2017_DevelopmentSet: Download failed [http://www.cs.tut.fi/sgn/arg/dcase2017/data/TUT-rare-sound-events-2017-development/TUT-rare-sound-events-2017-development.doc.zip] [None: None]
urllib.error.HTTPError: HTTP Error 404: Not Found
HTTP Error 404: Not Found

**Comment by toni-heittola** [comment]
Paths are corrected in commit c8faebf83601d499bbd2a6031acd61da6ad1f4ed. 

The dataset download URLs are old ones, as the dataset have been released in [Zenodo.org](https://zenodo.org/record/401395#.WwXQehy-m7A). The new download URL are updated in commit 145d9bbdfb3ca207d562902039530da101a5e397.
