### ISSUE TITLE
Code is not moving forward at Feature Normaliser step

### ISSUE THREAD

**Issue by sarang-rk** [TUT-ARG/DCASE2017-baseline-system#27]
Hi, I am running the code in AWS. Code is triggered from Task1.py. It is running fine from terminal. But whenever I am running the same from Rshiny app, it is getting stuck at following point.

method_progress = tqdm(current_normalizer_files,
                                       desc='           {0: >15s}'.format('Feature method(From Here) '),
                                       file=sys.stdout,
                                       leave=False,
                                       miniters=1,
                                       disable=self.disable_progress_bar,
                                       ascii=self.use_ascii_progress_bar)

It just hangs at this point. This has to do with tqdm I am not sure. 

You can see 
{'mfcc':Dir/Applications/system/task1/feature_normalizer/feature_extractor_a3d3864c319bc59fa2956d12a34e2900/scale_fold0.cpickle', 
'mfcc_delta': 'Dir/Applications/system/task1/feature_normalizer/feature_extractor_f17897bd2a133d1c1d1c853e491d2a3a/scale_fold0.cpickle', 
'mfcc_acceleration': '/Dir/Applications/system/task1/feature_normalizer/feature_extractor_68a40f5e3b77df9564aaa68c92e95be9/scale_fold0.cpickle'}

Getting loaded properly.

Please let me know if there is something wrong in it. 
Thanks in advance :)

**Comment by toni-heittola** [comment]
I have not run the code in AWS. You could try to run the code in so-called node-mode, with command `task1.py --node`. This will skip progress info through tqdm library. Instead normal print command is used.

**Comment by sarang-rk** [comment]
Thanks Toni :) surely I will try with this command. Also one silly question, by using DCASE framework, will I be able to detect sounds/scene in a new uploaded audio file. On which there is no training done. Please let me know your comments. Thanks in advance :) 👍

**Comment by toni-heittola** [comment]
The provided application code do not support classification/detection on arbitrary audio file. However, this can be implemented rather easily using DCASE framework by just extracting correct features and feeding them to the pre-trained acoustic model for the prediction. 

You might get poor performance if there is miss-matched conditions (microphone's frequency response, acoustics of the recordings situation, etc.) between training material and new input material.

**Comment by sarang-rk** [comment]
Hi Toni, I have considered following approach. 
1. Train the model on all the input files from DCASE dataset. 
2. Call the python program test1.py -d test 
3. Change the following parameter in Class TUTAcousticScenes_2017_EvaluationSet (under dataset.py) 
kwargs['storage_name'] = kwargs.get('storage_name', '') to 
kwargs['storage_name'] = kwargs.get('storage_name', 'TUT-acoustic-scenes-2017-test')
4. Keep a test audio file in TUT-acoustic-scenes-2017-test/audio/test_files.wav
5. Change the test.txt file under TUT-acoustic-scenes-2017-test/audio/evaluation_setup/test.txt to take all the testing files.
6. Record the output.

**Comment by toni-heittola** [comment]
This seems roughly correct approach. You might have to add also reference annotations to TUT-acoustic-scenes-2017-test/meta.csv to get evaluation stage working. Other option is to do evaluation outside the provided code.
