### ISSUE TITLE
 evalauations subtaskB in task4

### ISSUE THREAD

**Issue by MichelleYang2017** [TUT-ARG/DCASE2017-baseline-system#31]
I want to know can you provide a test funcation with me for evaluation subtaskb in task4

**Comment by toni-heittola** [comment]
Unfortunately, this repository does not implement a system for DCASE2017/Task4. That is implemented here > https://github.com/ankitshah009/Task-4-Large-scale-weakly-supervised-sound-event-detection-for-smart-cars

**Comment by MichelleYang2017** [comment]
thank you!

Toni Heittola <notifications@github.com> 于2019年8月8日周四 下午8:48写道：
