### ISSUE TITLE
Is there open source code for DCASE2017 Task2 Rare event detection?

### ISSUE THREAD

**Issue by happyprotean** [TUT-ARG/DCASE2017-baseline-system#32]
I check DCASE2017 Task2 result page but did not find any open source there.  Is this because all the authors didn't open their code or because I didn't search correctly?

**Comment by toni-heittola** [comment]
As far as I know, none of the challenge participants for DCASE2017 Task2 released their system code. However, this baseline system is released with rather permissive EULA, which in the essence allows academic usage and prevents commercial usage. Some of the later DCASE baseline systems have been released under MIT license.
