### ISSUE TITLE
python applications/task3.py crashes

### ISSUE THREAD

**Issue by longle2718** [TUT-ARG/DCASE2017-baseline-system#4]
[I] System training
[I] ==================================================
[I] 
           Fold           :   0%|                                                                                                | 0/4 [00:00<?, ?it/s'ascii' codec can't decode byte 0xda in position 1: ordinal not in range(128)                                                     | 0/1 [00:00<?, ?it/s]

**Comment by toni-heittola** [comment]
You are most likely running code in a console which does not support UTF-8 character set, and progress bar is using unicode character for bar graph by default (under Linux and Mac). To solve this you can do one of the following:

1. Set your console to support UTF-8 character set
2. Change parameter `general->use_ascii_progress_bar` to true in `applications/parameters/task3.defaults.yaml`
3. Run application with node flag `python task3.py -n` to disable progress bars

**Comment by longle2718** [comment]
Thank you so much for the prompt response!
I suspected it was the UTF-8 issue too, but it wasn't. In fact,
>> echo $LANG
en_US.UTF-8
(I'm on Ubuntu 16.04.2 LTS)

Also
>> python applications/task2.py -n crashes
File "/home/username/DCASE2017-baseline-system/dcase_framework/datasets.py", line 2144, in _generate_mixture_recipes
    zip(event_offsets_seconds[event_presence_flags], event_instance_ids[event_presence_flags])]
UnboundLocalError: local variable 'zip' referenced before assignment

**Comment by toni-heittola** [comment]
There was minor incompatibility between Python 2 and 3, which was causing problem when generating Task2 data. This is now corrected, see commit d578425a877c91bf9b16e7b42854611537290158.

**Comment by icestoneking** [comment]
[I] Initialize [Development setup][folds]
[I] ==================================================
[I] 
[I]   System              
[I]     Name                 : DCASE 2017::Sound Event Detection in Real-life Audio / Baseline System
[I]     Description          : DCASE2017 baseline (CPU) using DCASE2017 task 3 development dataset
[I]     Parameter set        : dcase2017
[I]     Setup                : Python[2.7.12], Numpy[1.14.2], sklearn[0.19.1], Keras[2.1.5], Theano[0.9.0], Librosa[0.6.0]
[I]   Dataset             
[I]     Name                 : TUT-sound-events-2017-development
[I]     Active folds         : [1, 2, 3, 4]
[I]   Evaluator           
[I]     Save path            : system/task3/evaluator
                                                                                                                                                                                                            [I]   DONE     [0:00:00.072976 ]                                                                                                                                                                            
[I] 
[I] Feature extractor
[I] ==================================================
[I] 
                                                                                                                                                                                                            [I]   DONE     [0:00:00.038335 ] [24 items] 
[I] 
[I] Feature normalizer
[I] ==================================================
[I] 
                                                                                                                                                                                                            [I]   DONE     [0:00:00.000938 ]                                                                                                                                                                            
[I] 
[I] System training
[I] ==================================================
[I] 
           Fold           :   0%|                                                                                                                                                     | 0/4 [00:00<?, ?it/s[D]   Validation     Scene :   0%|                                                                                                                                                     | 0/1 [00:00<?, ?it/s]
[D]     Valid sets found [427]                                                                                                                                                                              
[D]     Best fitting set ID=41, Error= 2.5%
[D]     Validation event counts in respect of all data:
[D]     Event label          | Amount (%) 
[D]     -------------------- + -------------------- 
[D]     people walking       | 9.00 
[D]     car                  | 11.00 
[D]     large vehicle        | 10.00 
[D]     brakes squeaking     | 4.00 
[D]     children             | 8.00 
[D]     people speaking      | 15.00 
[D]  
[D]   Training items 	[186542]
[D]   Validation items 	[24427]
[D]   Keras
[D]     Backend 	[theano]
[D]     BLAS library	[OpenBLAS]		(Threads[1])
[D]   Theano
[D]     Device 		[cpu]
[D]     floatX 		[float64]
[D]     Optimizer 	[None]
[D]     OpenMP		[False]
[D]   
[D]   Model summary
[D]     Layer type      | Output               | Param   | Name                   | Connected to                | Activ.  | Init   
[D]     --------------- + -------------------- + ------  + ---------------------  + --------------------------- + ------- + ------
Traceback (most recent call last):
  File "./task3.py", line 294, in <module>
    sys.exit(main(sys.argv))
  File "./task3.py", line 228, in main
    app.system_training()
  File "/home/shaolinpai/load/DCASE2017-baseline-system-1.2.0/dcase_framework/decorators.py", line 38, in function_wrapper
    to_return = func(*args, **kwargs)
  File "/home/shaolinpai/load/DCASE2017-baseline-system-1.2.0/dcase_framework/application_core.py", line 2190, in system_training
    data_filenames=data_filelist
  File "/home/shaolinpai/load/DCASE2017-baseline-system-1.2.0/dcase_framework/learners.py", line 2314, in learn
    self.log_model_summary()
  File "/home/shaolinpai/load/DCASE2017-baseline-system-1.2.0/dcase_framework/keras_utils.py", line 188, in log_model_summary
    for node_index, node in enumerate(layer.inbound_nodes):
AttributeError: 'Dense' object has no attribute 'inbound_nodes'

**Comment by icestoneking** [comment]
I'm sorry to occupy such a long space.^_^

**Comment by toni-heittola** [comment]
This is due to new Keras version (>=2.1.3), and some changes in the internal variable names. This should be fixed now with commit 14f4e3d73b347402d337c069bc297bf959a107f2.

**Comment by icestoneking** [comment]
Thank you so much for the prompt response!
According to your reply this question has been resolved.
Thank again~^_^

**Comment by weienzhang** [comment]
Today when i ran this command "python task3.py -n", it turns out the error like:
[D]   Feature vector 	[200]
[D]   Batch size 	[256]
[D]   Epochs 		[200]
[I]   Training
[I]           | Loss                | Metric              |                
[I]           | binary_crossentropy | binary_accuracy     |                
[I]     Epoch | Train    | Val      | Train    | Val      | Time           
[I]     ----- + -------- + -------- + -------- + -------- + ---------------
Traceback (most recent call last):
  File "task3.py", line 294, in <module>
    sys.exit(main(sys.argv))
  File "task3.py", line 228, in main
    app.system_training()
  File "/home/zwe/Downloads/DCASE2017-baseline-system-master/dcase_framework/decorators.py", line 38, in function_wrapper
    to_return = func(*args, **kwargs)
  File "/home/zwe/Downloads/DCASE2017-baseline-system-master/dcase_framework/application_core.py", line 2214, in system_training
    validation_files=validation_files
  File "/home/zwe/Downloads/DCASE2017-baseline-system-master/dcase_framework/learners.py", line 2468, in learn
    class_weight=class_weight
  File "/root/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1239, in fit
    validation_freq=validation_freq)
  File "/root/anaconda3/lib/python3.7/site-packages/keras/engine/training_arrays.py", line 192, in fit_loop
    callbacks._call_batch_hook('train', 'begin', batch_index, batch_logs)
  File "/root/anaconda3/lib/python3.7/site-packages/keras/callbacks/callbacks.py", line 84, in _call_batch_hook
    batch_hook = getattr(callback, hook_name)
AttributeError: 'ProgressLoggerCallback' object has no attribute 'on_train_batch_begin'

I just checked the code i downloaded from the github and the file "keras_utils.py" has changed according to the commit 14f4e3d, and i don't konw whether it is a problem with Keras version again?
