### ISSUE TITLE
Running the minimal parameters for Task 1

### ISSUE THREAD

**Issue by anasvaf** [TUT-ARG/DCASE2017-baseline-system#5]
Hello,

I am trying to test if the minimal system works for Task1. I am running it on a Windows 10 machine with python 2.7. It does the feature extraction, the feature normalization and I get the following error in the system evaluation.

Traceback (most recent call last):
  File "task1.py", line 287, in <module>
    sys.exit(main(sys.argv))
  File "task1.py", line 236, in main
    app.system_evaluation()
  File "D:\DCASE2017\dcase_framework\decorators.py", line 38, in function_wrapper
    to_return = func(*args, **kwargs)
  File "D:\DCASE2017\dcase_framework\application_core.py", line 1477, in system_evaluation
    estimated_scene_list=estimated_scene_list)
  File "C:\Continuum\Anaconda2\lib\site-packages\sed_eval\scene.py", line 148, in evaluate
    y_true.append(reference_item_matched['scene_label'])
**TypeError: list indices must be integers, not str**

**Comment by toni-heittola** [comment]
The system should also do system training and system testing before entering the system evaluation stage. Can you verify that those stages are ran also, e.g. check that "D:\DCASE2017\applications\system\task1\learner\*" contains acoustic models and "D:\DCASE2017\applications\system\task1\recognizer\*" contains system outputs.

**Comment by anasvaf** [comment]
the systems performs the training and testing. I get the error on the evaluation.
Also the folders learner and recognizer contain folders with "long" names
For instance there is a parameters.yaml file as following

_hash: **fbfd4a588dd63ed774bea2be8303b02a** --> Name of the folder
audio_error_handling: false
decision_making:
  enable: true
  type: maximum
enable: true
frame_accumulation:
  enable: true
  type: sum
frame_binarization:
  enable: false
  threshold: null
  type: frame_max

**Comment by toni-heittola** [comment]
This error occures when evaluator cannot find reference scene class label for the file to be evaluated. Of course this should not happen:) Can you check "results_fold1.txt" file, this can be found in the last subdirectory under D:\DCASE2017\applications\system\task1\recognizer\. The file should look like this:

audio/a025_110_120.wav	park
audio/a025_90_100.wav	home

**Comment by anasvaf** [comment]
The .txt file looks like this.
audio/a025_110_120.wav	park

audio/a025_90_100.wav	home

audio/a025_100_110.wav	park

audio/a025_80_90.wav	home

audio/a025_70_80.wav	park

etc.

**Comment by toni-heittola** [comment]
Hmm, there should not be any empty lines. You could send me the actual output file through email for debugging.

**Comment by toni-heittola** [comment]
This issue should have been resolved in commit 0d76390e72ae67127b91d36a40895e9255139662. Closing this issue.
