### ISSUE TITLE
[Win10+Anaconda]Weird result obtained, where should I look first?

### ISSUE THREAD

**Issue by lordet01** [TUT-ARG/DCASE2017-baseline-system#7]
Hello,

I setup the DECASE2017 baseline at my system (Win10, 64bit, Anaconda, Python 2.7)
It seems that every requirements were installed properly and No error was shown during operation.
However, final results looks really weird, since all F1 score shows NaN.
Here is my command to obtain the below's results

$ python ./applications/task2.py -o -s dcase2017_gpu

![image](https://user-images.githubusercontent.com/22748631/27724295-3c3f5f0a-5dac-11e7-963e-2a83d162742a.png)

It would be great if you share your opinion where should I look first to solve this issue.

Best regards,

**Comment by toni-heittola** [comment]
Does the system give reasonable scores  when run in CPU mode? 

$ python ./applications/task2.py -o -s dcase2017

**Comment by lordet01** [comment]
Dear T. Heittola

Thanks for quick reply.

Unfortunately, cpu mode also gives me NaN

- Kwang Myung Jeon

나의 iPhone에서 보냄

2017. 6. 30. 오후 4:14 Toni Heittola <notifications@github.com> 작성:

**Comment by toni-heittola** [comment]
Can you check if commit 54f4c6c2a065f544fe1b136538ce7ee6fcf8482b resolves your problem?

**Comment by lordet01** [comment]
Yes! problem solved after applying the commit mentioned above. Thank you for your help.

![image](https://user-images.githubusercontent.com/22748631/27829438-9ac7594e-60fc-11e7-8eb8-6cb6a2a9253e.png)
