### ISSUE TITLE
Multicore CPU

### ISSUE THREAD

**Issue by pabloriera** [TUT-ARG/DCASE2017-baseline-system#8]
Hi, I couldn't manage to use all the CPUs. I am trying with Task 1.

I set OpenMP to True and set for many threads as the computer CPUs

Is there anything else to do?

Thanks

**Comment by toni-heittola** [comment]
Usually enabling OpenMP should enable multicore processing. What platform your are running the system? What Python version you are using, are you using Anaconda? What BLAS library you are using?
